{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-payment-service.fullname" . }}-secrets
  labels:
    {{- include "core-payment-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
