replicaCount: 1

image:
  repository: ghcr.io/visiobook-esp/core-payment-service-dev
  tag: "sha-5deb880"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 8080

nameOverride: ""
fullnameOverride: "core-payment-service"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

istio:
  enabled: true
  injection: true

  virtualService:
    enabled: true
    hosts:
      - "core-payment-service"
      - "core-payment-service.visiobook.dev"
    gateways:
      - mesh
  destinationRule:
    enabled: true
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http1MaxPendingRequests: 100
          http2MaxRequests: 100
          maxRequestsPerConnection: 2
      loadBalancer:
        simple: ROUND_ROBIN
      outlierDetection:
        consecutiveErrors: 5
        interval: 30s
        baseEjectionTime: 30s

  mtls:
    enabled: true
    mode: ISTIO_MUTUAL

nodeSelector: {}
tolerations: []
affinity: {}

podLabels:
  app: core-payment-service
  version: "latest"
  app.kubernetes.io/name: core-payment-service
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: backend

resources: {}
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0  # l'ancien pod reste vivant tant que le nouveau n'est pas prêt
    maxSurge: 1        # autorise 1 pod en plus pendant le rollout

revisionHistoryLimit: 3 # nombre de revision garder sur un pod
progressDeadlineSeconds: 60 # temps max pour que le pod soit opérationnel avant de considérer que le déploiement a échoué
minReadySeconds: 10 # le pod doit être stable 10s avant d'être considéré Available (évite les faux positifs)
terminationGracePeriodSeconds: 10 # délai avant SIGKILL (30s par défaut, réduit pour les tests)

existingSecret: ""
existingMinioSecret: ""

env:
  APP_NAME: core-payment-service
  APP_VERSION: 0.1.0
  APP_PORT: "8087"
  API_PREFIX: /api/v1
  NODE_ENV: production
  LOG_LEVEL: info
  SWAGGER_ENABLED: "false"
  DATABASE_SERVICE_URL: http://core-database-service.visiobook-namespace.svc.cluster.local:8095
  USER_SERVICE_URL: http://core-user-service.visiobook-namespace.svc.cluster.local:8081
  NOTIFICATION_SERVICE_URL: http://core-notification-service.visiobook-namespace.svc.cluster.local:8088
  REDIS_HOST: redis.visiobook-namespace.svc.cluster.local
  REDIS_PORT: "6379"
